---
- name: Install programs from packages
  pacman:
    name: "{{ programs.packages }}"
  when: programs.packages
  tags:
    - programs

- name: Install programs from aur
  aur:
    name: "{{ programs.aur }}"
  become: true
  become_user: aur_builder
  when: programs.aur
  tags:
    - aur
    - programs