---
- hosts: localhost
  become: yes

  vars_prompt:
    - name: user_password
      prompt: "Enter desired user password"
      private: yes
      confirm: yes

  roles:
    - { role: base, tags: ["base"] }
    - { role: gnupg, tags: ["gnupg"] }
