---
- hosts: localhost
  become: yes

  vars_prompt:
    - name: user_password
      prompt: "Enter desired user password"
      private: yes
      confirm: yes

  roles:
    - { role: base, tags: ["base"] }
    - { role: gnupg, tags: ["gnupg"] }
    - { role: cron, tags: ["cron"] }
    - { role: ssh, tags: ["ssh"] }
    - { role: dotfiles, tags: ["dotfiles"] }
    - {
        role: interception,
        tags: ["interception"],
        when: "interception is defined",
      }
    - { role: fonts, tags: ["fonts"] }
    - { role: x, tags: ["x"] }
    - { role: lightdm, tags: ["lightdm"], when: "display_manager == 'lightdm'" }
    - {
        role: xmonad,
        tags: ["xmonad"],
        when: "desktop_environment == 'xmonad'",
      }
    - { role: laptop, tags: ["laptop"] }
