---
- hosts: localhost
  become: yes

  vars_prompt:
    - name: user_password
      prompt: "Enter desired user password"
      private: yes
      confirm: yes

    - name: github_password
      prompt: "Enter github account password for private dotfiles and password-store"
      private: yes
      confirm: yes

  roles:
    - { role: system, tags: ["system"] }
    - { role: user, tags: ["user"] }
    - { role: gnupg, tags: ["gnupg"] }
    - { role: cron, tags: ["cron"] }
    - { role: ssh, tags: ["ssh"] }
    - { role: pass, tags: ["pass"] }
    - {
        role: interception,
        tags: ["interception"],
        when: "interception is defined",
      }
    - { role: fonts, tags: ["fonts"] }
    - { role: x, tags: ["x"] }
    - { role: lightdm, tags: ["lightdm"], when: "display_manager == 'lightdm'" }
    - {
        role: xmonad,
        tags: ["xmonad"],
        when: "desktop_environment == 'xmonad'",
      }
    - { role: programs, tags: ["programs"] }
    - { role: virtualbox, tags: ["virtualbox"] }
    - { role: laptop, tags: ["laptop"], when: "laptop|bool == True" }
    - { role: snapper, tags: ["snapper"] }
