---
- name: Create aur_builder user
  user:
    name: aur_builder
    group: wheel
  tags:
    - aur
    - system

- name: Create ansible dir
  file:
    path: "/home/aur_builder/.ansible"
    state: directory
  become: true
  become_user: aur_builder
  tags:
    - aur
    - system

- name: Create ansible temp dir
  file:
    path: "/home/aur_builder/.ansible/tmp"
    state: directory
    mode: "0700"
  become: true
  become_user: aur_builder
  tags:
    - aur
    - system

- name: Add aur_builder to NOPASSWD sudo
  lineinfile:
    path: /etc/sudoers.d/11-install-aur_builder
    line: "aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman"
    create: yes
    validate: "visudo -cf %s"
  tags:
    - aur
    - user
    - system

- name: "Install {{ aur.helper }}"
  aur:
    name: "{{ aur.helper }}"
  become: true
  become_user: aur_builder
  tags:
    - aur
    - system

- name: Install AUR base packages now
  aur:
    name: "{{ aur.packages }}"
  become: true
  become_user: aur_builder
  tags:
    - aur
    - system
    - packages
