---
- name: Install LightDM
  pacman:
    name:
      - lightdm
      - lightdm-webkit-theme-litarvan
  tags:
    - lightdm

- name: "Install {{ lightdm.greeter_package }}"
  pacman:
    name: "{{ lightdm.greeter_package }}"
  when: lightdm.greeter_package is defined
  tags:
    - lightdm

- name: "Install {{ lightdm.greeter_aur }}"
  aur:
    name: "{{ lightdm.greeter_aur }}"
  become: true
  become_user: aur_builder
  when: lightdm.greeter_aur is defined
  tags:
    - lightdm
    - aur

- name: "Set the greeter to {{ lightdm.greeter_name }}"
  lineinfile:
    dest: /etc/lightdm/lightdm.conf
    regexp: '^greeter-session^'
    line: "greeter-session={{ lightdm.greeter_name }}"
    state: present
    create: yes
  tags:
    - lightdm

- name: "Install {{ lightdm.theme_package }}"
  pacman:
    name: "{{ lightdm.theme_package }}"
  when: lightdm.theme_package is defined
  tags:
    - lightdm

- name: "Install {{ lightdm.theme_aur }}"
  aur:
    name: "{{ lightdm.theme_aur }}"
  become: true
  become_user: aur_builder
  when: lightdm.theme_aur is defined
  tags:
    - lightdm
    - aur

- name: "Set the theme to {{ lightdm.theme_name }}"
  lineinfile:
    dest: "/etc/lightdm/{{ lightdm.greeter_conf }}"
    regexp: "^webkit_theme"
    line: "webkit_theme={{ lightdm.theme_name }}"
    state: present
    create: yes
  when: lightdm.theme_name is defined
  tags:
    - lightdm

- name: Create background dir
  file:
    path: /usr/share/backgrounds
    state: directory
    group: "{{ user.group }}"
    mode: "0775"
  tags:
    - lightdm

- name: Clone wallpapers for lightdm
  git:
    repo: "{{ wallpapers.url }}"
    dest: /usr/share/backgrounds/wallpapers
    accept_hostkey: yes
    update: no
  when: wallpapers.url is defined
  become: true
  become_user: "{{ user.name }}"
  tags:
    - lightdm

- name: Enable LightDM
  service: name=lightdm.service enabled=yes
  tags:
    - lightdm
