---
- name: Install LightDM
  pacman:
    name:
      - lightdm
      - lightdm-webkit2-greeter

- name: Install lightdm webkit greeter Aether theme
  aur: name=lightdm-webkit-theme-aether
  become: true
  become_user: aur_builder
  tags:
    - aur

- name: Enable LightDM
  service: name=lightdm.service enabled=yes

- name: Switch the greeter to webkit2
  lineinfile:
    dest: /etc/lightdm/lightdm.conf
    regexp: "^greeter-session="
    line: greeter-session=lightdm-webkit2-greeter
    state: present
    create: yes

- name: Switch webkit2 greeter theme to Aether
  lineinfile:
    dest: /etc/lightdm/lightdm-webkit2-greeter.conf
    regexp: "^webkit_theme="
    line: webkit_theme=lightdm-webkit-theme-aether
    state: present
    create: yes

- name: Create background dir
  file:
    path: /usr/share/backgrounds
    state: directory
    group: "{{ user.group }}"
    mode: "0775"

- name: Push LightDM greeter background
  copy: src=the-great-wave-off-kanagawa-wallpaper.jpg dest=/usr/share/backgrounds/the-great-wave-off-kanagawa-wallpaper.jpg
# - name: Specify LightDM greeter background
#   lineinfile: dest=/etc/lightdm/lightdm-gtk-greeter.conf
#     regexp="^background="
#     state=present
#     line="background=/usr/share/backgrounds/onosendai.jpg"

# - name: Hide user images
#   lineinfile: dest=/etc/lightdm/lightdm-gtk-greeter.conf
#     regexp="^hide-user-image="
#     state=present
#     line="hide-user-image=true"

# - name: Force LightDM greeter theme
#   lineinfile: dest=/usr/share/xgreeters/lightdm-gtk-greeter.desktop
#     regexp="^Exec="
#     state=present
#     line="Exec=env GTK_THEME=Adwaita:dark lightdm-gtk-greeter"
