---
- name: Copy pacman configuration file
  copy:
    src: pacman.conf
    dest: /etc/pacman.conf

- name: Refresh pacman mirrors
  pacman:
    update_cache: yes

- name: Install inetutils for hostname
  pacman:
    name: inetutils
    state: present

- name: Set the hostname
  hostname:
    name: "{{ hostname }}"
  when: hostname is defined

- name: Set kernel parameters
  lineinfile:
    dest: /etc/default/grub
    regexp: "^GRUB_CMDLINE_LINUX_DEFAULT"
    state: present
    line: 'GRUB_CMDLINE_LINUX_DEFAULT="{{ kernel_parameters }}"'
  when: kernel_parameters is defined and bootloader == 'grub'
  notify:
    - rebuild grub
  tags:
    - kernelparams

- name: Create aur_builder user
  user:
    name: aur_builder
    group: wheel
  tags:
    - aur
    - user

- name: Add aur_builder to NOPASSWD sudo
  lineinfile:
    path: /etc/sudoers.d/11-install-aur_builder
    line: "aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman"
    create: yes
    validate: "visudo -cf %s"
  tags:
    - aur
    - user

# install yay now so that aur module can use it
- name: Install yay
  aur:
    name: yay
  become: true
  become_user: aur_builder
  tags:
    - aur
    - user

- include: shell.yml
- include: user.yml
- include: sudo.yml
- include: snapper.yml
- include: packages.yml
- include: journal.yml
