---
- name: Install xmonad and xmobar packages
  pacman:
    name: "{{ window_managers.xmonad.packages }}"
  when: window_managers.xmonad.packages
  tags:
    - xmonad

- name: Install xmonad and xmobar aur
  aur:
    name: "{{ window_managers.xmonad.aur }}"
  become: true
  become_user: aur_builder
  when: window_managers.xmonad.aur
  tags:
    - xmonad
    - aur

- name: Install window managers package utilities
  pacman:
    name: "{{ window_managers.utils.packages }}"
  when: window_managers.utils.packages
  tags:
    - xmonad

- name: Install window managers aur utilities
  aur:
    name: "{{ window_managers.utils.aur }}"
  become: true
  become_user: aur_builder
  when: window_managers.utils.aur
  tags:
    - xmonad
    - aur

# - name: Install py3status
#   pacman: name=py3status state=present

- name: Verify header in default applications file
  lineinfile:
    dest: /etc/xdg/mimeapps.list
    state: present
    line: "[Default Applications]"
    insertbefore: BOF
    create: yes
  tags:
    - xmonad

# sudo systemctl enable betterlockscreen@$USER